# Generated by Django 3.0.6 on 2020-06-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssuranceMaladie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
